export const CategoryConstant={
    CATEGORY_ADDING:"CATEGORY_ADDING",
    CATEGORY_ADDED_SUCCESSFULLY:"CATEGORY_ADDED_SUCCESSFULLY",
    CATEGORY_ADDING_FAILED:"CATEGORY_ADDING_FAILED",

    CATEGORY_UPDATED:"CATEGORY_UPDATED",
    CATEGORY_FETCHED:"CATEGORY_FETCHED"

}