export const ContactUsConstants={
    CONTACTUS_ADDING:"CONTACTUS_ADDING",
    CONTACTUS_ADDED_SUCCESSFULLY:"CONTACTUS_ADDED_SUCCESSFULLY",
    CONTACTUS_ADDING_FAILED:"CONTACTUS_ADDING_FAILED",
    
    CONTACTUS_FORM_UPDATED:"CONTACTUS_FORM_UPDATED",
    CONTACTUS_FETCHED:"CONTACTUS_FETCHED"
}
