export const ProductConstants={
    PRODUCT_ADDING:"PRODUCT_ADDING",
    PRODUCT_ADDED_SUCCESSFULLY:"PRODUCT_ADDED_SUCCESSFULLY",
    PRODUCT_ADDING_FAILED:"PRODUCT_ADDING_FAILED",
    
    PRODUCT_FORM_UPDATED:"PRODUCT_FORM_UPDATED",
    PRODUCT_FETCHED:"PRODUCT_FETCHED"
}