export const ProductfeaturesConstants={
    PRODUCTFEATURE_ADDING:"PRODUCTFEATURE_ADDING",
    PRODUCTFEATURE_ADDED_SUCCESSFULLY:"PRODUCTFEATURE_ADDED_SUCCESSFULLY",
    PRODUCTFEATURE_ADDING_FAILED:"PRODUCTFEATURE_ADDING_FAILED",

    PRODUCTFEATURE_FORM_UPDATE:"PRODUCTFEATURE_FORM_UPDATE",
    PRODUCTFEATURE_FETCH:"PRODUCTFEATURE_FETCH",
}