export const SubcategoryConstants={
    SUBCATEGORY_ADDING:"SUBCATEGORY_ADDING",
    SUBCATEGORY_ADDED_SUCCESSFULLY:"SUBCATEGORY_ADDED_SUCCESSFULLY",
    SUBCATEGORY_ADDING_FAILED:"SUBCATEGORY_ADDING_FAILED",

    SUBCATEGORY_UPDATED:"SUBCATEGORY_UPDATED",
    SUBCATEGORY_FETCHED:"SUBCATEGORY_FETCHED"

}