export const UsersConstants={
    USER_ADDING:"USER_ADDING",
    USER_ADDED_SUCCESSFULLY:"USER_ADDED_SUCCESSFULLY",
    USER_ADDING_FAILED:"USER_ADDING_FAILED",

    USER_FETCH:" USER_FETCH",
    USER_FORM_UPDATE:"USER_FORM_UPDATE",
}