export const UsertypeConstants={
    USER_TYPE_ADDING:"USER_TYPE_ADDING",
    USER_TYPE_ADDED_SUCCESSFULLY:"USER_TYPE_ADDED_SUCCESSFULLY",
    USER_TYPE_ADDING_FAILED:"USER_TYPE_ADDING_FAILED",

    USER_TYPE_UPDATED:" USER_TYPE_UPDATED",

    USER_TYPE_FETCH:"USER_TYPE_FETCH"

}